version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: com.github.Fernthedev:FernAPI
    versions:
    - ">= 7.0.a, < 7.1"
  - dependency-name: io.netty:netty-tcnative-boringssl-static
    versions:
    - 2.0.36.Final
    - 2.0.38.Final
  - dependency-name: com.velocitypowered:velocity-api
    versions:
    - 1.1.3
    - 1.1.4
  - dependency-name: org.projectlombok:lombok
    versions:
    - 1.18.16
    - 1.18.18
  - dependency-name: org.jetbrains.kotlinx:kotlinx-coroutines-core
    versions:
    - 1.4.2-native-mt
